import { PrismaClient } from '@prisma/client';
import * as bcrypt from 'bcrypt';

const prisma = new PrismaClient();

const SALT_ROUNDS = 12;

const adminUsers = [
	{
		email: 'miyuru@nanaska.com',
		name: 'Miyuru',
		role: 'superadmin' as const,
		password: 'password',
	},
	{
		email: 'info@nanaska.com',
		name: 'Nanaska Admin',
		role: 'admin' as const,
		password: 'password',
	},
];

const lecturers = [
	{
		name: 'Channa Gunawardana',
		title: 'Lead Lecturer & CEO',
		credentials: ['CIMA Fellow', 'CA Sri Lanka', 'MBA Finance', 'PhD (Candidate)'],
		bio: "Channa Gunawardana, CEO of a public listed company in Sri Lanka, is a fellow member of CIMA UK and CA Sri Lanka. He holds a Bachelor's degree in Accountancy and Financial Management from the University of Sri Jayewardenepura and an MBA in Finance from the University of Southern Queensland, Australia. He is currently pursuing a PhD at Management and Science University, Malaysia.",
		bio2: 'With 21 years of lecturing experience, he is renowned as the CIMA case study specialist, having produced over 95% of CIMA Sri Lanka prize winners, including global prize winners over the last decade. He is also a member of the CIMA Global Council.',
		imageUrl: '/images/2021-04-Channa.png',
		stats: [
			{ number: '21+', label: 'Years Lecturing' },
			{ number: '95%', label: 'Prize Winners' },
			{ number: '10+', label: 'Global Winners' },
		],
		specialties: ['CIMA Case Study', 'Strategic Level', 'Management Level', 'Operational Level'],
		sortOrder: 1,
	},
	{
		name: 'Aloka Seneviratne',
		title: 'Lecturer – E3 Strategic Management',
		credentials: ['CIMA Passed Finalist', 'DipM', 'BSc Hons Engineering Physics'],
		bio: 'Praveen Aloka Seneviratne brings a wealth of knowledge and experience, holding a BSc Hons in Engineering Physics along with credentials as a CIMA Passed Finalist and DipM. His diverse academic background and professional expertise make him a valuable asset to the Nanaska faculty.',
		bio2: "Aloka's dedication to education and his ability to convey complex concepts with clarity will undoubtedly inspire and empower students. He is the E3 lecturer at Nanaska.",
		imageUrl: '/images/2024-07-DSC_0454-Copy-1.png',
		stats: [
			{ number: 'E3', label: 'Specialist' },
			{ number: 'CIMA', label: 'Passed Finalist' },
			{ number: 'BSc', label: 'Engineering Physics' },
		],
		specialties: ['E3 Strategic Management', 'Business Strategy', 'Leadership'],
		sortOrder: 2,
	},
	{
		name: 'Indika Rajakaruna',
		title: 'Lecturer – P3 Risk Management',
		credentials: ['CISA – ISCA (USA)', 'AIB (IBSL)', 'PG Ex.Dip Bank Mgt', 'Executive MSc Marketing'],
		bio: 'Indika Rajakaruna is a banker by profession in the Governance, Risk and Control field who counts over 25 years of exposure in the banking industry. He currently leads a team of audit professionals in a listed bank awarded both titles of Best Bank and Best Digital Bank in Sri Lanka.',
		bio2: 'He is the First and Only Accredited Trainer in Sri Lanka for the CISA (Certified Information Systems Auditor) by ISACA–USA, and serves as Director for Corporate Relations of ISACA–Sri Lanka Chapter. He covers Cyber Risk within P3 at Nanaska.',
		imageUrl: '/images/2021-04-Indika.png',
		stats: [
			{ number: '25+', label: 'Years in Banking' },
			{ number: '#1', label: 'CISA Trainer SL' },
			{ number: 'P3', label: 'Risk Specialist' },
		],
		specialties: ['P3 Risk Management', 'Cybersecurity', 'IS Auditing', 'Enterprise Risk'],
		sortOrder: 3,
	},
	{
		name: 'Ruchira Perera',
		title: 'Lecturer – F3 Financial Strategy',
		credentials: ['BSc Accountancy (USJ)', 'First Class MBA (PIM)', 'ACMA', 'CPA', 'FCMA (SL)'],
		bio: 'Mr. Ruchira Perera is a graduate of the University of Sri Jayewardenepura with a first class in Accountancy and Financial Management. He holds an MBA from the Postgraduate Institute of Management and is professionally qualified with CPA (Australia), CIMA (UK) and CMA (SL).',
		bio2: 'He has nearly two decades of industry experience in senior roles including CFO and Financial Controller. He is a Governing Council Member of CMA Sri Lanka and a Technical Advisor to SAFA, and is pursuing his Doctorate at Lincoln University College, Malaysia.',
		imageUrl: '/images/2022-05-ruchi-1.png',
		stats: [
			{ number: '18+', label: 'Years in Finance' },
			{ number: 'CFO', label: 'Multinational Exp.' },
			{ number: 'F3', label: 'Specialist' },
		],
		specialties: ['F3 Financial Strategy', 'Corporate Finance', 'M&A', 'Capital Markets'],
		sortOrder: 4,
	},
	{
		name: 'Shervin Perera',
		title: 'Lecturer – F2 & BA3',
		credentials: ['ACMA (UK)', 'CGMA', 'MBA (UOS)'],
		bio: 'Shervin Perera holds impressive credentials including ACMA (UK), CGMA, and an MBA from the University of Southampton. His extensive expertise in management accounting and business analysis is invaluable as he teaches the F2 and BA3 subjects.',
		bio2: "Mr. Perera's commitment to academic excellence and practical insights will greatly benefit students, equipping them with the knowledge and skills needed to excel in their professional careers.",
		imageUrl: '/images/2024-06-Shervin_Perera-removebg-preview.png',
		stats: [
			{ number: 'F2', label: 'Specialist' },
			{ number: 'MBA', label: 'Univ. Southampton' },
			{ number: 'ACMA', label: 'UK Qualified' },
		],
		specialties: ['F2 Advanced Financial Reporting', 'BA3', 'Management Accounting'],
		sortOrder: 5,
	},
	{
		name: 'Mark Gunathilake',
		title: 'Lecturer – P2, OCS & BA2',
		credentials: ['BSc Hons (USJ)', 'ACMA', 'CGMA', 'SCS Prize Winner'],
		bio: "Mark Gunathilake is a Passed Finalist of the Chartered Institute of Management Accountants. He also holds a 1st Class Bachelor's Degree in Accountancy from the University of Sri Jayewardenepura.",
		bio2: 'Having started off his career at one of the big 4 audit firms, he brings over 3 years of experience across Manufacturing, Transportation and Retail. As a former CIMA SCS Prize Winner, he gives students a unique practical edge in their preparation.',
		imageUrl: '/images/2025-01-Untitled-design-11.png',
		stats: [
			{ number: '🥇', label: 'SCS Prize Winner' },
			{ number: 'P2', label: 'OCS & BA2' },
			{ number: 'Big 4', label: 'Alumni' },
		],
		specialties: ['P2 Management Accounting', 'OCS Case Study', 'BA2'],
		sortOrder: 6,
	},
	{
		name: 'Osmand Fernando',
		title: 'Lecturer',
		credentials: ['MBA (UK)', 'ACMA', 'CGMA'],
		bio: 'Osmand Fernando holds an MBA from the United Kingdom and ACMA/CGMA qualifications, bringing international perspective and professional finance expertise to Nanaska students.',
		bio2: 'His international academic background combined with professional qualifications equips him to deliver high-quality, globally-relevant CIMA tuition.',
		imageUrl: '/images/2024-07-IMG_6966-1copy.png',
		stats: [
			{ number: 'MBA', label: 'UK Qualified' },
			{ number: 'ACMA', label: 'CGMA' },
			{ number: '🌐', label: 'International' },
		],
		specialties: ['Management Accounting', 'Financial Strategy', 'Business Analysis'],
		sortOrder: 7,
	},
	{
		name: 'Lasantha Vidanagamage',
		title: 'Lecturer – P2 Advanced Management Accounting',
		credentials: ['CIMA Passed Finalist', 'MPAcc (USJ)', 'BPharm (USJ)'],
		bio: 'Lasantha Vidanagamage is a CIMA pass finalist and holds both a Master of Professional Accounting (MPAcc) and a Bachelor of Pharmacy (BPharm) from the University of Sri Jayewardenepura.',
		bio2: 'He teaches P2 – Advanced Management Accounting. His diverse academic background and extensive expertise in management accounting provide students with a comprehensive and practical learning experience.',
		imageUrl: '/images/2024-07-441312389_467371879000666_851286037044610417_n-copy-1.png',
		stats: [
			{ number: 'P2', label: 'Specialist' },
			{ number: 'MPAcc', label: 'USJ Graduate' },
			{ number: 'CIMA', label: 'Passed Finalist' },
		],
		specialties: ['P2 Advanced Management Accounting'],
		sortOrder: 8,
	},
	{
		name: 'Sanuda Minuraka',
		title: 'Lecturer – BA1',
		credentials: ['BSc Hons 1st Class (Plymouth UK)', 'CIMA Passed Finalist'],
		bio: 'Sanuda Minuraka holds a First-Class Honors degree in Accounting & Finance from Plymouth University, UK, reflecting his academic excellence and in-depth knowledge of the field.',
		bio2: 'As a CIMA Passed Finalist, Sanuda combines his strong theoretical foundation with practical insights into management accounting, making his teaching highly engaging and relevant to real-world applications.',
		imageUrl: '/images/2025-01-Untitled-design-12.png',
		stats: [
			{ number: '1st', label: 'Class Hons (UK)' },
			{ number: 'BA1', label: 'Specialist' },
			{ number: 'CIMA', label: 'Passed Finalist' },
		],
		specialties: ['BA1 Business Economics', 'Management Accounting'],
		sortOrder: 9,
	},
	{
		name: 'Janith Jayasinghe',
		title: 'Lecturer – Law & HRM',
		credentials: ['LB (Hons)', 'Affiliate CIPM', 'Attorney-at-Law', 'Notary Public', 'Company Secretary'],
		bio: 'Janith Jayasinghe is a multifaceted professional excelling in both the legal and human resources domains. Holding an LB (Hons) degree and a Professional Qualification in HRM from CIPM, he is an Attorney-at-Law, Notary Public, Commissioner for Oaths, and a Company Secretary.',
		bio2: 'As an Affiliate CIPM, Janith brings a unique blend of legal expertise and HR management proficiency, making him a well-rounded professional in his field.',
		imageUrl: '/images/2025-01-Untitled-design-15.png',
		stats: [
			{ number: 'LLB', label: 'Honours' },
			{ number: 'CIPM', label: 'Affiliate' },
			{ number: '⚖️', label: 'Attorney-at-Law' },
		],
		specialties: ['Business Law', 'Corporate Governance', 'HRM', 'Ethics'],
		sortOrder: 10,
	},
	{
		name: 'Ali Raheem',
		title: 'Lecturer – BA2',
		credentials: ['BSc (USJ)', 'CIMA Exams Complete'],
		bio: "Ali Raheem is a CIMA passed finalist, having completed the qualification within a span of 2 years. He is a product of St. Peter's College, Colombo and is currently an Undergraduate at the University of Sri Jayewardenepura.",
		bio2: 'Ali has been an assistant lecturer at Nanaska since 2019 and he is the BA2 lecturer at Nanaska.',
		imageUrl: '/images/2025-01-Untitled-design-13.png',
		stats: [
			{ number: '2yrs', label: 'CIMA Completed' },
			{ number: 'BA2', label: 'Specialist' },
			{ number: '2019', label: 'At Nanaska' },
		],
		specialties: ['BA2 Management Accounting', 'Business Economics'],
		sortOrder: 11,
	},
];

const defaultSettings = [
	{ key: 'google_analytics_id', value: '', category: 'analytics', label: 'Google Analytics Measurement ID' },
	{ key: 'meta_pixel_id', value: '', category: 'analytics', label: 'Meta Pixel ID' },
	{ key: 'payment_gateway_client_id', value: '', category: 'payment', label: 'Payment Gateway Client ID' },
	{ key: 'payment_gateway_secret', value: '', category: 'payment', label: 'Payment Gateway Secret' },
	{ key: 'payment_success_url', value: '/payment-success', category: 'payment', label: 'Payment Success URL' },
	{ key: 'payment_cancel_url', value: '/payment-cancel', category: 'payment', label: 'Payment Cancel URL' },
	{ key: 'site_name', value: 'Nanaska', category: 'general', label: 'Site Name' },
	{ key: 's3_bucket_url', value: '', category: 'storage', label: 'S3 Bucket URL' },
	{ key: 'sse_endpoint', value: '', category: 'sse', label: 'SSE Events Endpoint' },

	{ key: 'ipg_gbp_client_id', value: '14004406', category: 'payment', label: 'IPG GBP Client ID' },
	{ key: 'ipg_lkr_client_id', value: '14004606', category: 'payment', label: 'IPG LKR Client ID' },
	{ key: 'contact_phones', value: JSON.stringify(['+94 77 499 7338', '+94 77 711 8902', '+94 112 575 016']), category: 'contact', label: 'Contact Phone Numbers (JSON array)' },
	{ key: 'contact_email', value: 'info@nanaska.com', category: 'contact', label: 'Contact Email' },
	{ key: 'contact_address', value: 'No. 464/1/1, Galle Road, Colombo 03, Sri Lanka', category: 'contact', label: 'Office Address' },
	{ key: 'contact_map_lat', value: '6.8955', category: 'contact', label: 'Map Latitude' },
	{ key: 'contact_map_lng', value: '79.8527', category: 'contact', label: 'Map Longitude' },
];

const subjects = [
	{
		id: `BA1`,
		name: `Fundamentals of Business Economics`,
		price: 16000,
		level: `certificate`,
		slug: `ba1-fundamentals-of-business-economics`,
		description: `BA1 provides a thorough grounding in micro and macroeconomics, exploring how businesses operate within global markets. Students examine the economic environment and its impact on business decisions and performance.`,
		icon: `📊`,
		subtitle: `Enterprise, economics & the global business environment`,
		highlights: [`Microeconomics — supply, demand and market equilibrium`, `Macroeconomics — GDP, inflation, interest rates`, `International trade and globalisation`, `Business cycles and economic indicators`, `Government policy and its effects on business`, `Financial markets and institutions`],
		syllabus: [{ "topic": "The Global Business Environment", "desc": "Understanding how political, economic, social, and technological forces shape the business landscape." }, { "topic": "Microeconomic Analysis", "desc": "Supply and demand, price elasticity, market structures and competitive behaviour." }, { "topic": "Macroeconomic Policy", "desc": "Fiscal and monetary policy tools and their effects on business and investment." }, { "topic": "International Trade & Finance", "desc": "Exchange rates, balance of payments, international trade agreements and protectionism." }, { "topic": "Financial Markets & Institutions", "desc": "Role of financial intermediaries, capital markets, and the banking system." }],
		outcomes: [`Explain the role of markets and pricing mechanisms in resource allocation.`, `Analyse macroeconomic data and assess the impact on business strategy.`, `Evaluate international trade patterns and the effects of exchange rate movements.`, `Understand the function of financial institutions and capital markets.`, `Apply economic principles to business decision-making scenarios.`],
	},
	{
		id: `BA2`,
		name: `Fundamentals of Management Accounting`,
		price: 16000,
		level: `certificate`,
		slug: `ba2-fundamentals-of-management-accounting`,
		description: `BA2 covers the core principles of management accounting, equipping students with skills to gather, analyse and use cost and management information to support planning, control and decision-making within organisations.`,
		icon: `🧮`,
		subtitle: `Costing, budgeting and management information systems`,
		highlights: [`Cost classification and behaviour`, `Absorption and marginal costing methods`, `Budgeting and budgetary control`, `Standard costing and variance analysis`, `Cost–volume–profit (CVP) analysis`, `Decision-making techniques`],
		syllabus: [{ "topic": "Costing Principles", "desc": "Cost objects, cost classification, direct/indirect costs and cost behaviour." }, { "topic": "Costing Methods", "desc": "Job, batch, process and service costing, absorption vs marginal costing." }, { "topic": "Budgeting", "desc": "Preparing functional and master budgets, flexed budgets and budgetary control." }, { "topic": "Standard Costing", "desc": "Setting standards, calculating variances and interpreting results." }, { "topic": "Decision Making", "desc": "CVP analysis, relevant costs, limiting factors and short-run decisions." }],
		outcomes: [`Prepare and interpret cost statements using various costing methods.`, `Construct and analyse budgets to support financial planning and control.`, `Calculate and interpret standard cost variances.`, `Apply relevant costing principles to short-term business decisions.`, `Understand the role of management accounting in supporting organisational strategy.`],
	},
	{
		id: `BA3`,
		name: `Fundamentals of Financial Accounting`,
		price: 16000,
		level: `certificate`,
		slug: `ba3-fundamentals-of-financial-accounting`,
		description: `BA3 introduces students to financial accounting and the preparation of financial statements. It covers the regulatory framework, accounting principles, double-entry bookkeeping, and the preparation of financial statements for sole traders, partnerships and companies.`,
		icon: `📑`,
		subtitle: `Financial reporting, the accounting equation & double-entry bookkeeping`,
		highlights: [`Double-entry bookkeeping principles`, `Preparation of trial balance and financial statements`, `Accounting for assets, liabilities and equity`, `Accruals, prepayments and provisions`, `Partnership accounts`, `Introduction to company accounts`],
		syllabus: [{ "topic": "Accounting Fundamentals", "desc": "The accounting equation, double-entry system and the accounting cycle." }, { "topic": "Preparing Financial Statements", "desc": "Income statements, balance sheets and cash flow statements for different entity types." }, { "topic": "Accounting Adjustments", "desc": "Depreciation, accruals, prepayments, bad debts and provisions." }, { "topic": "Partnership Accounts", "desc": "Appropriation accounts, capital and current accounts, admission and retirement of partners." }, { "topic": "Introduction to Company Accounts", "desc": "Share capital, retained earnings, basic presentation under IFRS." }],
		outcomes: [`Apply double-entry bookkeeping to record business transactions accurately.`, `Prepare trial balances and basic financial statements.`, `Account for common adjustments such as depreciation and accruals.`, `Prepare financial statements for partnerships and sole traders.`, `Understand the basic structure of company financial statements.`],
	},
	{
		id: `BA4`,
		name: `Fundamentals of Ethics, Corporate Governance and Business Law`,
		price: 16000,
		level: `certificate`,
		slug: `ba4-fundamentals-of-ethics-corporate-governance-and-business-law`,
		description: `BA4 provides the ethical and legal grounding that underpins the CIMA qualification. Students study corporate governance frameworks, professional ethics, sustainability and the legal context within which businesses operate.`,
		icon: `⚖️`,
		subtitle: `Ethics, governance frameworks and the legal context of business`,
		highlights: [`CIMA Code of Ethics and professional conduct`, `Corporate governance principles and frameworks`, `Sustainability and integrated reporting`, `Contract law and employment law basics`, `Company law and directors' duties`, `Data protection and cybersecurity awareness`],
		syllabus: [{ "topic": "Business Ethics", "desc": "Ethical frameworks, professional scepticism and resolution of ethical dilemmas." }, { "topic": "Corporate Governance", "desc": "Governance codes, board structures, audit committees and shareholder rights." }, { "topic": "Sustainability & Integrated Reporting", "desc": "<IR> Framework, ESG considerations and non-financial reporting." }, { "topic": "Business Law Essentials", "desc": "Formation and enforcement of contracts, consumer protection and employment law." }, { "topic": "Company Law", "desc": "Company formation, share capital, directors' duties and insolvency basics." }],
		outcomes: [`Apply the CIMA Code of Ethics to identify and resolve professional ethical issues.`, `Explain the principles of good corporate governance and their significance.`, `Discuss sustainability reporting and integrated thinking.`, `Understand key elements of contract law and employment law.`, `Outline the legal duties of company directors and the rights of shareholders.`],
	},
	{
		id: `E1`,
		name: `Managing Finance in a Digital World`,
		price: 25000,
		level: `operational`,
		slug: `e1-managing-finance-in-a-digital-world`,
		description: `E1 examines the evolving role of the finance function in a digital business environment. Students explore digital technologies, data analytics, automation and the changing skills required of finance professionals.`,
		icon: `💻`,
		subtitle: `The role of finance and digital technologies in business`,
		highlights: [`The digital finance function and its evolution`, `Data analytics and business intelligence`, `Automation, RPA and AI in finance`, `Cloud computing and ERP systems`, `Cybersecurity and data governance`, `Digital transformation strategy`],
		syllabus: [{ "topic": "The Finance Function", "desc": "Role of finance in modern organisations, shared services and finance business partnering." }, { "topic": "Digital Technologies", "desc": "Big data, analytics, automation, AI and machine learning in finance." }, { "topic": "Information Systems", "desc": "ERP systems, cloud computing, data management and governance." }, { "topic": "Data Security & Ethics", "desc": "Cybersecurity risks, data protection regulations and ethical use of data." }, { "topic": "Digital Strategy", "desc": "Supporting digital transformation and change management within finance." }],
		outcomes: [`Explain how digital technologies are transforming the finance function.`, `Evaluate the use of data analytics and automation in financial processes.`, `Assess the risks and benefits of cloud-based and ERP systems.`, `Apply principles of data governance and cybersecurity in a finance context.`, `Support digital transformation initiatives within organisations.`],
	},
	{
		id: `F1`,
		name: `Financial Reporting`,
		price: 25000,
		level: `operational`,
		slug: `f1-financial-reporting`,
		description: `F1 develops students' ability to prepare and interpret financial statements for individual companies and groups in accordance with IFRS. Topics include consolidation, financial instruments and reporting frameworks.`,
		icon: `📋`,
		subtitle: `Preparation and analysis of financial statements under IFRS`,
		highlights: [`IFRS conceptual framework`, `Preparation of single entity financial statements`, `Group accounts — consolidation basics`, `Revenue recognition (IFRS 15)`, `Leases (IFRS 16)`, `Financial instruments overview`],
		syllabus: [{ "topic": "The Financial Reporting Framework", "desc": "IASB conceptual framework, qualitative characteristics and the standard-setting process." }, { "topic": "Single Entity Financial Statements", "desc": "P&L, OCI, balance sheet, cash flow statement and notes under IFRS." }, { "topic": "Group Accounts", "desc": "Consolidation, elimination of intra-group transactions, goodwill and non-controlling interests." }, { "topic": "Key IFRS Standards", "desc": "IFRS 15 (Revenue), IFRS 16 (Leases), IFRS 9 (Financial Instruments)." }, { "topic": "Interpretation & Analysis", "desc": "Ratio analysis, horizontal/vertical analysis and limitations of financial statements." }],
		outcomes: [`Prepare financial statements for single entities in accordance with IFRS.`, `Construct basic consolidated financial statements including goodwill calculations.`, `Apply key IFRS standards including IFRS 15, 16 and IFRS 9.`, `Analyse and interpret financial statements using key ratios.`, `Explain the role and authority of the IASB and national standard setters.`],
	},
	{
		id: `P1`,
		name: `Management Accounting`,
		price: 25000,
		level: `operational`,
		slug: `p1-management-accounting`,
		description: `P1 advances students' management accounting skills, covering advanced costing techniques, pricing strategies, performance measurement, and risk in the context of planning and control within organisations.`,
		icon: `📈`,
		subtitle: `Advanced costing, planning, control and performance measurement`,
		highlights: [`Activity-based costing (ABC)`, `Target costing and value engineering`, `Transfer pricing`, `Throughput accounting`, `Pricing strategies`, `Budgetary control and beyond budgeting`],
		syllabus: [{ "topic": "Advanced Costing Techniques", "desc": "ABC, throughput accounting, life-cycle costing and target costing." }, { "topic": "Pricing Decisions", "desc": "Pricing strategies, price elasticity, market-based and cost-plus pricing." }, { "topic": "Short-run Decisions", "desc": "Relevant costing, limiting factors, make or buy, and shutdown decisions." }, { "topic": "Planning & Budgeting", "desc": "Budgetary systems, beyond budgeting, rolling forecasts and zero-based budgeting." }, { "topic": "Performance Management", "desc": "Financial and non-financial KPIs, balanced scorecard, responsibility centres." }],
		outcomes: [`Apply advanced costing techniques including ABC and throughput accounting.`, `Make pricing decisions using both cost-based and market-based approaches.`, `Analyse short-run operational decisions using relevant costing principles.`, `Design and evaluate budgeting systems appropriate to the organisation.`, `Select and apply performance measurement frameworks including the balanced scorecard.`],
	},
	{
		id: `OCS`,
		name: `Operational Case Study`,
		price: 26650,
		level: `operational`,
		slug: `operational-case-study`,
		description: `The Operational Case Study (OCS) is a three-hour integrated assessment that tests students' ability to apply knowledge from E1, F1 and P1 in a realistic business scenario. It assesses professional skills including communication, analysis and judgement.`,
		icon: `🏗️`,
		subtitle: `Integrated assessment combining E1, F1 and P1`,
		highlights: [`Integration of E1, F1 and P1 knowledge`, `Realistic business scenario with pre-seen material`, `Analysis and application of operational finance skills`, `Professional communication and report writing`, `Commercial awareness and judgement`],
		syllabus: [{ "topic": "Pre-Seen Analysis", "desc": "Analysing the case study context, industry, business model and strategic position." }, { "topic": "Financial Reporting Application", "desc": "Applying F1 knowledge to prepare and interpret financial information in context." }, { "topic": "Management Accounting Application", "desc": "Using P1 tools for costing, budgeting and performance measurement in the scenario." }, { "topic": "Digital Finance in Context", "desc": "Applying E1 digital concepts within the operational business scenario." }, { "topic": "Exam Technique", "desc": "Time management, answering variant tasks and presenting professional-quality responses." }],
		outcomes: [`Integrate knowledge across E1, F1 and P1 to address complex operational issues.`, `Analyse a business scenario using financial and non-financial information.`, `Produce professional-quality written responses tailored to senior management audiences.`, `Demonstrate commercial awareness and sound business judgement.`, `Perform effectively under exam conditions with structured time management.`],
	},
	{
		id: `E2`,
		name: `Managing Performance`,
		price: 25000,
		level: `management`,
		slug: `e2-managing-performance`,
		description: `E2 examines how organisations manage performance and relationships in modern dynamic environments. Students explore project management, people management, digital innovation and the management of change across complex organisations.`,
		icon: `🏎️`,
		subtitle: `Project management, business relationships and leading change`,
		highlights: [`Organisational structure and governance`, `Project management methodologies (PRINCE2, Agile)`, `Stakeholder engagement and communication`, `Change management models`, `People management and motivation theories`, `Managing digital transformation projects`],
		syllabus: [{ "topic": "Organisational Structures", "desc": "Types of organisation, governance frameworks and how structures enable performance." }, { "topic": "Project Management", "desc": "Project life cycle, planning, scheduling, risk management and benefits realisation." }, { "topic": "People & Change Management", "desc": "Leadership styles, motivation theory, managing resistance and organisational change models." }, { "topic": "Stakeholder Management", "desc": "Identifying, analysing and communicating with diverse stakeholder groups." }, { "topic": "Digital & Innovation", "desc": "Managing digital change projects, agile approaches and disruptive innovation." }],
		outcomes: [`Evaluate organisational structures and governance frameworks.`, `Plan and manage projects using appropriate methodologies.`, `Apply people management and change management models in business contexts.`, `Develop stakeholder communication and engagement strategies.`, `Manage digital transformation and innovation within finance teams.`],
	},
	{
		id: `P2`,
		name: `Advanced Management Accounting`,
		price: 25000,
		level: `management`,
		slug: `p2-advanced-management-accounting`,
		description: `P2 extends management accounting into advanced territory — covering advanced variance analysis, decision theory under uncertainty, capital investment appraisal, and strategic performance measurement systems.`,
		icon: `📐`,
		subtitle: `Advanced planning, control and decision-making techniques`,
		highlights: [`Advanced variance analysis — planning vs operational variances`, `Decision-making under uncertainty (maximin, maximax, minimax regret)`, `Risk and uncertainty analysis`, `Capital investment appraisal (NPV, IRR, ARR)`, `Strategy and performance measurement`, `Divisional performance — ROI, RI and EVA`],
		syllabus: [{ "topic": "Advanced Variance Analysis", "desc": "Planning and operational variances, mix and yield variances for materials and sales." }, { "topic": "Uncertainty & Decision Theory", "desc": "Expected values, sensitivity analysis, decision trees and scenario analysis." }, { "topic": "Long-run Decisions", "desc": "NPV, IRR, payback, ARR \u2014 selecting and evaluating capital investment projects." }, { "topic": "Divisional Performance", "desc": "ROI, residual income, Economic Value Added (EVA) and transfer pricing." }, { "topic": "Strategy & Control", "desc": "Strategic performance frameworks, management control systems and risk." }],
		outcomes: [`Calculate and interpret advanced variance analysis including planning variances.`, `Apply decision theory techniques to problems involving risk and uncertainty.`, `Evaluate capital investment proposals using discounted cash flow methods.`, `Assess divisional performance using ROI, RI and EVA.`, `Design and critique strategic management control and performance measurement systems.`],
	},
	{
		id: `F2`,
		name: `Advanced Financial Reporting`,
		price: 25000,
		level: `management`,
		slug: `f2-advanced-financial-reporting`,
		description: `F2 advances financial reporting into complex territory — covering complex group structures, financial instruments, share-based payments, impairment, and a critical evaluation of financial reporting standards.`,
		icon: `📰`,
		subtitle: `Complex IFRS, group accounts and financial analysis`,
		highlights: [`Complex group consolidations (associates, JVs)`, `Financial instruments — IFRS 9 in depth`, `Share-based payments (IFRS 2)`, `Impairment of assets (IAS 36)`, `Earnings per share (IAS 33)`, `Evaluation and critique of IFRS standards`],
		syllabus: [{ "topic": "Complex Group Accounts", "desc": "Consolidation of associates (IAS 28), joint ventures and complex subsidiary structures." }, { "topic": "Financial Instruments", "desc": "IFRS 9 \u2014 classification, measurement, impairment and hedge accounting." }, { "topic": "Advanced IFRS Standards", "desc": "IFRS 2 (share-based payment), IAS 36 (impairment), IAS 33 (EPS), IFRS 17 (insurance)." }, { "topic": "Reporting in Specialised Situations", "desc": "Foreign exchange, hyperinflation, segment reporting and discontinuing operations." }, { "topic": "Critical Evaluation", "desc": "Limitations of IFRS, debates on fair value, and current developments in financial reporting." }],
		outcomes: [`Prepare consolidated financial statements including associates and joint ventures.`, `Apply IFRS 9 to classify, measure and impair financial instruments.`, `Account for share-based payments and complex provisions.`, `Critically evaluate financial reporting standards and their application.`, `Analyse and interpret complex group financial statements.`],
	},
	{
		id: `MCS`,
		name: `Management Case Study`,
		price: 27675,
		level: `management`,
		slug: `management-case-study`,
		description: `The Management Case Study (MCS) is a three-hour integrated exam set within a realistic management-level business scenario. It tests the application of E2, P2 and F2 knowledge with particular emphasis on financial analysis, management control and strategic decision support.`,
		icon: `🏢`,
		subtitle: `Integrated assessment combining E2, P2 and F2`,
		highlights: [`Integration of E2, P2 and F2 knowledge`, `Realistic management-level business scenario`, `Strategic financial analysis and decision-making`, `Management control and performance measurement`, `Stakeholder communication and professional judgement`, `Expert case study coaching by Channa Gunawardana`],
		syllabus: [{ "topic": "Pre-Seen Mastery", "desc": "Thorough analysis of the pre-seen material including financials, industry context and strategy." }, { "topic": "Management Accounting Application", "desc": "Using P2 techniques in the MCS scenario for performance analysis and decision support." }, { "topic": "Financial Reporting Application", "desc": "Applying F2 standards and analysis within management reporting contexts." }, { "topic": "Managing Performance in Context", "desc": "Using E2 frameworks for project management, stakeholder and change issues in the scenario." }, { "topic": "Exam Strategy & Mock Practice", "desc": "Full mock exams in Nanaska's exam engine, time management and marking review sessions." }],
		outcomes: [`Integrate E2, P2 and F2 knowledge within a management-level business context.`, `Evaluate complex management accounting issues and recommend solutions.`, `Prepare clear, professional reports and briefings for senior management audiences.`, `Apply change management and project management concepts to case scenario situations.`, `Manage exam time effectively and produce high-quality responses across all tasks.`],
	},
	{
		id: `E3`,
		name: `Strategic Management`,
		price: 25000,
		level: `strategic`,
		slug: `e3-strategic-management`,
		description: `E3 covers the formulation, evaluation and implementation of strategy at the enterprise level. Students analyse the competitive environment, develop strategic options, manage strategic risk and lead organisational change to deliver the strategy.`,
		icon: `🗺️`,
		subtitle: `Formulating and implementing competitive business strategy`,
		highlights: [`Strategic analysis — PESTLE, Porter's Five Forces, SWOT`, `Corporate strategy — Ansoff matrix, BCG portfolio`, `Competitive strategy — differentiation, cost leadership`, `Innovation and disruptive strategy`, `Strategic implementation and change management`, `Corporate social responsibility and sustainability`],
		syllabus: [{ "topic": "Strategic Position Analysis", "desc": "External environment analysis (PESTLE), industry analysis (Porter's Five Forces) and internal capability assessment." }, { "topic": "Strategic Choices", "desc": "Growth strategies, diversification, mergers & acquisitions, alliances and corporate portfolio management." }, { "topic": "Competitive Advantage", "desc": "Porter's generic strategies, value chain analysis, resource-based view and dynamic capabilities." }, { "topic": "Innovation & Digital Strategy", "desc": "Disruptive innovation, digital business models and strategic responses to technological change." }, { "topic": "Strategy Implementation", "desc": "Change management, organisational alignment, culture, leadership and balanced scorecard." }],
		outcomes: [`Conduct comprehensive strategic analysis using key analytical frameworks.`, `Evaluate strategic options and recommend the most appropriate strategy.`, `Design strategies for competitive advantage in complex market environments.`, `Lead strategic implementation including change, culture and performance alignment.`, `Integrate sustainability and CSR considerations into strategic decision-making.`],
	},
	{
		id: `P3`,
		name: `Risk Management`,
		price: 25000,
		level: `strategic`,
		slug: `p3-risk-management`,
		description: `P3 equips students with the tools and frameworks to identify, assess, quantify and manage risks facing complex organisations. Topics include enterprise risk management, treasury management, financial risk instruments and cybersecurity.`,
		icon: `🛡️`,
		subtitle: `Identifying, assessing and managing enterprise-level risk`,
		highlights: [`Enterprise Risk Management (ERM) frameworks — COSO, ISO 31000`, `Financial risk — interest rate, currency, credit and liquidity risk`, `Treasury management and hedging strategies`, `Derivatives — futures, options, swaps and FRAs`, `Cybersecurity risk and governance`, `Business continuity and resilience planning`],
		syllabus: [{ "topic": "Enterprise Risk Management", "desc": "Risk identification, assessment, appetite, tolerance and ERM frameworks (COSO, ISO 31000)." }, { "topic": "Financial Risks & Treasury", "desc": "Interest rate risk, foreign currency risk, credit risk, liquidity risk and treasury policy." }, { "topic": "Hedging Instruments", "desc": "Forward contracts, futures, options, swaps and interest rate instruments \u2014 calculation and strategy." }, { "topic": "Cybersecurity & Technology Risk", "desc": "IT governance, cybersecurity frameworks (CISA knowledge), data protection and incident response." }, { "topic": "Business Continuity", "desc": "BCP planning, disaster recovery, resilience strategies and crisis management." }],
		outcomes: [`Apply ERM frameworks to identify and prioritise enterprise risks.`, `Calculate and evaluate strategies for managing financial risks including FX and interest rate risk.`, `Select and price appropriate derivative instruments for hedging purposes.`, `Assess cybersecurity risks and recommend governance controls.`, `Develop and evaluate business continuity and resilience plans.`],
	},
	{
		id: `F3`,
		name: `Financial Strategy`,
		price: 25000,
		level: `strategic`,
		slug: `f3-financial-strategy`,
		description: `F3 covers the advanced corporate finance topics required for financial leadership. Students evaluate financing, dividend and investment decisions; value businesses; and advise on mergers, acquisitions and complex financial strategy questions.`,
		icon: `💎`,
		subtitle: `Corporate finance, valuation and strategic financial decision-making`,
		highlights: [`Capital structure theory — Modigliani-Miller, WACC`, `Business valuation methods — DCF, multiples, EVA`, `Dividend policy and payout decisions`, `Mergers & acquisitions — valuation and financing`, `Initial Public Offerings (IPOs) and capital markets`, `International financial management`],
		syllabus: [{ "topic": "Corporate Financing Decisions", "desc": "Sources of finance, capital structure theories, gearing and the cost of capital (WACC)." }, { "topic": "Business Valuation", "desc": "Asset-based, income-based (DCF) and market-based valuation methods and their application." }, { "topic": "Mergers & Acquisitions", "desc": "M&A rationale, valuation of targets, financing structures, due diligence and integration." }, { "topic": "Dividend Policy", "desc": "Dividend theories, payout ratios, scrip dividends, buybacks and signalling." }, { "topic": "International Financial Management", "desc": "Cross-border financing, transfer pricing, political risk and international capital markets." }],
		outcomes: [`Evaluate corporate financing decisions and optimise the capital structure.`, `Value businesses using multiple approaches and advise on M&A transactions.`, `Formulate dividend policy recommendations for diverse stakeholder groups.`, `Advise on the financial strategy for complex international businesses.`, `Apply advanced corporate finance theory to strategic financial decisions.`],
	},
	{
		id: `SCS`,
		name: `Strategic Case Study`,
		price: 30750,
		level: `strategic`,
		slug: `strategic-case-study`,
		description: `The Strategic Case Study (SCS) is CIMA's most demanding integrated exam, testing mastery of E3, P3 and F3 within a complex, board-level business scenario. Success in the SCS, combined with the CIMA experience requirement, awards the CGMA designation.`,
		icon: `🌐`,
		subtitle: `The final integrated assessment — combining E3, P3 and F3`,
		highlights: [`Integration of E3, P3 and F3 at board level`, `Complex pre-seen with full organisation simulation`, `Board-level strategic recommendations and reports`, `Financial strategy and risk management application`, `Corporate governance and ethical decision-making`],
		syllabus: [{ "topic": "Strategic Position Mastery", "desc": "In-depth analysis of the pre-seen: industry, competitive position, financial health and strategy." }, { "topic": "Financial Strategy Application", "desc": "Using F3 knowledge \u2014 valuations, M&A analysis, financing decisions \u2014 in the board scenario." }, { "topic": "Risk Management Application", "desc": "P3 frameworks applied to identify, evaluate and manage strategic and financial risks in context." }, { "topic": "Strategic Leadership", "desc": "E3 tools \u2014 strategic analysis, competitive positioning, CSR and sustainability in the SCS scenario." }, { "topic": "SCS Exam Technique", "desc": "Full mock SCS exams, marking review with Channa Gunawardana and response structuring workshops." }],
		outcomes: [`Produce board-level strategic reports integrating E3, P3 and F3 knowledge.`, `Evaluate complex strategic situations and recommend financially sound decisions.`, `Manage enterprise risk and financial strategy at the highest organisational level.`, `Apply governance and ethical principles within complex real-world scenarios.`, `Achieve the CGMA designation upon passing the SCS and fulfilling the experience requirement.`],
	},
];

// Helper to generate all non-empty subsets (power set) of an array
function generatePowerSet<T>(arr: T[]): T[][] {
	const result: T[][] = [];
	const n = arr.length;
	// Iterate through all possible binary combinations (2^n - 1, excluding empty set)
	for (let i = 1; i < (1 << n); i++) {
		const subset: T[] = [];
		for (let j = 0; j < n; j++) {
			if (i & (1 << j)) {
				subset.push(arr[j]);
			}
		}
		result.push(subset);
	}
	return result;
}

// Course price lookup map (LKR)
const COURSE_PRICES: Record<string, number> = {
	BA1: 16000, BA2: 16000, BA3: 16000, BA4: 16000,
	E1: 25000, P1: 25000, F1: 25000, OCS: 26650,
	E2: 25000, P2: 25000, F2: 25000, MCS: 27675,
	E3: 25000, P3: 25000, F3: 25000, SCS: 30750,
};

// Course price lookup map (GBP) — fallback to proportional conversion if not set
const COURSE_PRICES_GBP: Record<string, number> = {
	BA1: 105, BA2: 105, BA3: 105, BA4: 105,
	E1: 175, P1: 175, F1: 175, OCS: 399,
	E2: 175, P2: 175, F2: 175, MCS: 499,
	E3: 175, P3: 175, F3: 175, SCS: 599,
};

// Level definitions — which courses belong to which level
const LEVEL_COURSE_GROUPS = {
	certificate: ['BA1', 'BA2', 'BA3', 'BA4'],
	operational: ['E1', 'P1', 'F1', 'OCS'],
	management: ['E2', 'P2', 'F2', 'MCS'],
	strategic: ['E3', 'P3', 'F3', 'SCS'],
};

// Explicit price overrides for both full-level packages and single-subject combinations
const COMBINATION_PRICE_OVERRIDES: Record<string, { price?: number; priceGbp?: number; name?: string; slug?: string }> = {
	// Full-level packages
	cert_full: { name: 'CIMA Certificate Level', slug: 'cima-certificate-level', price: 55000, priceGbp: 360 },
	op_full: { name: 'CIMA Operational Level', slug: 'cima-operational-level', price: 75000, priceGbp: 600 },
	mg_full: { name: 'CIMA Management Level', slug: 'cima-management-level', price: 77775, priceGbp: 600 },
	st_full: { name: 'CIMA Strategic Level', slug: 'cima-strategic-level', price: 105750, priceGbp: 600 },
	// Single-subject operational pricing (matches frontend display prices)
	op_e1: { price: 25000, priceGbp: 200 },
	op_f1: { price: 25000, priceGbp: 200 },
	op_p1: { price: 25000, priceGbp: 200 },
	// Single-subject management pricing (matches frontend display prices)
	mg_e2: { price: 25000, priceGbp: 200 },
	mg_f2: { price: 25000, priceGbp: 200 },
	mg_p2: { price: 25000, priceGbp: 200 },
	mg_mcs: { price: 27675, priceGbp: 499 },
	// Single-subject strategic pricing (matches frontend display prices)
	st_e3: { price: 25000, priceGbp: 200 },
	st_f3: { price: 25000, priceGbp: 200 },
	st_p3: { price: 25000, priceGbp: 200 },
	st_scs: { price: 30750, priceGbp: 599 },
	// Two-subject combinations at operational/management/strategic levels
	op_e1_f1: { price: 58000, priceGbp: 0 },
	op_e1_p1: { price: 58000, priceGbp: 0 },
	op_f1_p1: { price: 58000, priceGbp: 0 },
	mg_f2_p2: { price: 70000, priceGbp: 0 },
	st_e3_p3: { price: 80000, priceGbp: 0 },
};

// Generate all possible combinations for all levels
function generateCombinations() {
	const result: any[] = [];

	// Level key to prefix map
	const levelPrefixes: Record<string, string> = {
		certificate: 'cert',
		operational: 'op',
		management: 'mg',
		strategic: 'st',
	};

	for (const [levelKey, courseCodes] of Object.entries(LEVEL_COURSE_GROUPS)) {
		const prefix = levelPrefixes[levelKey] || levelKey.slice(0, 2);
		const allSubsets = generatePowerSet(courseCodes);

		for (const subset of allSubsets) {
			// Sort for consistent ID generation
			const sorted = [...subset].sort();
			const idSuffix = sorted.map(c => c.toLowerCase()).join('_');
			const comboId = `${prefix}_${idSuffix}`;

			// Calculate default price as sum of individual course prices
			const priceLkr = sorted.reduce((sum, code) => sum + (COURSE_PRICES[code] || 0), 0);
			const priceGbp = sorted.reduce((sum, code) => sum + (COURSE_PRICES_GBP[code] || 0), 0);

			// Check if there's a specific override for this combination
			const override = COMBINATION_PRICE_OVERRIDES[comboId];

			result.push({
				id: comboId,
				level: levelKey,
				subjects: sorted,
				price: override?.price ?? priceLkr,
				priceGbp: override?.priceGbp ?? priceGbp,
				name: override?.name ?? '',
				slug: override?.slug ?? null,
			});
		}
	}

	return result;
}

const combinations = generateCombinations();

const testimonials = [
	{
		studentName: `Fuseini Awiagah`,
		country: `Ghana`,
		flag: `🇬🇭`,
		tag: `SCS`,
		exam: `Strategic Case Study`,
		period: `Aug 2024`,
		year: 2024,
		marks: 80,
		imageUrl: `/images/2024-10-WhatsApp-Image-2024-10-13-at-15.03.21_43435e43.jpg`,
		quote: `Mr. Channa and Mr. Ali Raheem from the Nanaska team are by far the best tutors for CIMA SCS. Their ability to breakdown theories and invoke students' critical thinking abilities is remarkable. Their exceptional support along with study materials such as power mock made the learning process much easier than I had anticipated. I owe my pass mark to Nanaska.`,
		videoUrl: undefined,
		badge: undefined,
		isPrizeWinner: false,
		published: true,
		sortOrder: 1,
	},
	{
		studentName: `Ammar Ilyas`,
		country: `Sri Lanka`,
		flag: `🇱🇰`,
		tag: `SCS`,
		exam: `Strategic Case Study`,
		period: `May 2024`,
		year: 2024,
		marks: 99,
		imageUrl: `/images/2024-10-ammar-scs-copy.jpg`,
		quote: `Nanaska is unique because it offers an "all-you-need" source to pass your CIMA exams on the first attempt. The lecturers are well-versed with the reality of the exams and practice what they teach in their daily lives. All you need to do is to do exactly as the lecturers say!`,
		videoUrl: undefined,
		badge: undefined,
		isPrizeWinner: false,
		published: true,
		sortOrder: 2,
	},
	{
		studentName: `Sandun Ediriweera`,
		country: `Sri Lanka`,
		flag: `🇱🇰`,
		tag: `SCS`,
		exam: `Strategic Case Study`,
		period: `May 2024`,
		year: 2024,
		marks: 90,
		imageUrl: `/images/2024-10-Sandun-SCS-copy.jpg`,
		quote: `I am grateful for NANASKA and its exceptional lecturers, especially Channa Sir, for helping me successfully complete the strategic level case study. The program's strengths are effective answering techniques, in-depth business analysis, realistic mock exams, comprehensive theory refreshers, one-to-one mentoring, lecturers' expertise, and high-quality mock papers, which were key to my success. I highly recommend NANASKA for anyone aiming to excel in their strategic level case study.`,
		videoUrl: undefined,
		badge: undefined,
		isPrizeWinner: false,
		published: true,
		sortOrder: 3,
	},
	{
		studentName: `Suheelan Ramanathan`,
		country: `Malaysia`,
		flag: `🇲🇾`,
		tag: `SCS`,
		exam: `Strategic Case Study`,
		period: `May 2024`,
		year: 2024,
		marks: 83,
		imageUrl: `/images/2024-10-Suheelan-scs-copy.png`,
		quote: `I am glad to be part of Nanaska. The lecturers were incredibly knowledgeable and supportive, guiding me through every step of my learning journey. The learning approach allowed me to improve my business acumen skills and helped me to think in a strategic perspective when planning long term business goals. I used the case study materials extensively, and found the pre-seen analysis and mock exams were solid preparation for the actual exams. I felt prepared and confident that I had a full grasp of the scenarios and could deliver strong answers to the questions. Special thanks to Mr. Chana Gunawardana and Mr. Ali Raheem for helping to make this long time dream a reality.`,
		videoUrl: undefined,
		badge: undefined,
		isPrizeWinner: false,
		published: true,
		sortOrder: 4,
	},
	{
		studentName: `Chenuka Pasindu`,
		country: `Sri Lanka`,
		flag: `🇱🇰`,
		tag: `MCS`,
		exam: `Management Case Study`,
		period: `May 2024`,
		year: 2024,
		marks: 98,
		imageUrl: `/images/2024-10-Chenuka-MCS-copy.jpg`,
		quote: `I am thrilled to share that I recently passed the CIMA Management Case Study exam with 98 marks, and I owe a great deal of my success to Nanaska. After a five-year break from CIMA, I felt out of touch with the subject matter. However, the incredible support and guidance from Nanaska, particularly Channa Sir, made all the difference. Channa Sir's lecturing skills are exceptional. Even though the classes were online, they felt just like being in a physical classroom. His engaging teaching style, clear explanations, and practical insights helped me grasp complex concepts with ease. The mock exams and the detailed feedback I received were invaluable. They not only highlighted my strengths and weaknesses but also provided me with a clear roadmap to improve. The constructive criticism and encouragement from the Nanaska staff, including Channa Sir, played a crucial role in my preparation. Nanaska's comprehensive approach and dedicated team helped me navigate through the CIMA syllabus efficiently, boosting my confidence and knowledge. I am grateful for their unwavering support and highly recommend their services to anyone pursuing CIMA.`,
		videoUrl: undefined,
		badge: undefined,
		isPrizeWinner: false,
		published: true,
		sortOrder: 5,
	},
	{
		studentName: `Chamod Deshitha`,
		country: `Sri Lanka`,
		flag: `🇱🇰`,
		tag: `MCS`,
		exam: `Management Case Study`,
		period: `May 2024`,
		year: 2024,
		marks: 92,
		imageUrl: `/images/2024-10-Chamod-MCS-copy.jpg`,
		quote: `A colleague's recommendation led me to Mr. Channa Gunawardana's CIMA Management Case Study classes at Nanaska. Even though most classes were online, the classes were very engaging and enjoyable, replicating the energy of a physical classroom. I was able to pass the Management Level Case Study on my first attempt. Mr. Channa's guidance and the support of the Nanaska Team played a vital role in my success. I highly recommend Nanaska for anyone who is preparing for their CIMA exams.`,
		videoUrl: undefined,
		badge: undefined,
		isPrizeWinner: false,
		published: true,
		sortOrder: 6,
	},
	{
		studentName: `Isuru Perera`,
		country: `Sri Lanka`,
		flag: `🇱🇰`,
		tag: `MCS`,
		exam: `Management Case Study`,
		period: `May 2024`,
		year: 2024,
		marks: 110,
		imageUrl: `/images/2024-10-Isuru-MCS-copy.jpg`,
		quote: `I want to express my heartfelt gratitude to Mr. Channa Gunawardhana and the entire Nanaska team for their invaluable support in helping me pass the management case study. Without their guidance, this would have been a daunting challenge. Their mentorship showed me the path to success in tackling the management case study. Additionally, the study materials provided by Nanaska, including the mock exams and resources like KYP, KYI, and power mocks, played a crucial role in eliminating my exam anxieties and preparing me thoroughly for the final assessment.`,
		videoUrl: undefined,
		badge: undefined,
		isPrizeWinner: false,
		published: true,
		sortOrder: 7,
	},
	{
		studentName: `Shalika Nilmini`,
		country: `Sri Lanka`,
		flag: `🇱🇰`,
		tag: `MCS`,
		exam: `Management Case Study`,
		period: `May 2024`,
		year: 2024,
		marks: 85,
		imageUrl: `/images/2024-10-Shalika-MCS-copy.jpg`,
		quote: `I am thrilled to share my experience of successfully completing the CIMA Management Case Study under the guidance of Channa Sir and his exceptional team at Nanaska. The journey was challenging yet immensely rewarding, and I owe much of my success to their unwavering support and expertise. From the very beginning, Channa Sir and his team provided comprehensive study materials, insightful lectures, and personalized feedback that were instrumental in my preparation. Their deep understanding of the CIMA curriculum and practical business scenarios helped me bridge the gap between theory and real-world application.`,
		videoUrl: undefined,
		badge: undefined,
		isPrizeWinner: false,
		published: true,
		sortOrder: 8,
	},
	{
		studentName: `Salaama Sanoon`,
		country: `Sri Lanka`,
		flag: `🇱🇰`,
		tag: `OCS`,
		exam: `Operational Case Study`,
		period: `May 2024`,
		year: 2024,
		marks: 108,
		imageUrl: `/images/2024-10-Salaama-OCS-copy.jpg`,
		quote: `I would like to sincerely thank the entire team including the lecturers and the staff at Nanaska for their unwavering support and commitment in helping me pass my OCS exam with confidence. The refresh theory sessions conducted by the lecturers and the mocks given were extremely helpful as they covered every possible area that could be tested in the exam. The one on one attention that was given to us after completing our mocks helped me to correct my mistakes and improve.`,
		videoUrl: undefined,
		badge: undefined,
		isPrizeWinner: false,
		published: true,
		sortOrder: 9,
	},
	{
		studentName: `Umasha Malgalla`,
		country: `Sri Lanka`,
		flag: `🇱🇰`,
		tag: `MCS`,
		exam: `Management Case Study`,
		period: `May 2024`,
		year: 2024,
		marks: 83,
		imageUrl: `/images/2024-10-Umasha-MCS-copy.jpg`,
		quote: `Thanks to the guidance of Channa sir and the support of the Nanaska team, I have successfully passed my MSC case study. The lectures, strategies, and mock exams they provided were invaluable in preparing me for this examination. Additionally, the one-on-one discussions and detailed feedback on marked mocks were helpful in clarifying all my doubts and to enhance my confidence to face the exam well. I am deeply grateful for their unwavering support and dedication. Therefore, I highly recommend Channa sir and the services of the Nanaska team to any student striving for success in CIMA exams.`,
		videoUrl: undefined,
		badge: undefined,
		isPrizeWinner: false,
		published: true,
		sortOrder: 10,
	},
	{
		studentName: `Supipi Kandegedara`,
		country: `Sri Lanka`,
		flag: `🇱🇰`,
		tag: `MCS`,
		exam: `Management Case Study`,
		period: `May 2024`,
		year: 2024,
		marks: 86,
		imageUrl: `/images/2024-10-beautiful-blonde-woman-with-makeup-avatar-for-a-beauty-salon-illustration-in-the-cartoon-style-vector.jpg`,
		quote: `I am happy to share my experience with Nanaska, which played a pivotal role in my success in the MCS exams. From the moment I enrolled, I was impressed by the comprehensive and well-structured curriculum designed to cover all aspects of the MCS syllabus. The interactive classes, combined with practical case studies and real-world examples, helped me grasp complex concepts with ease. Additionally, the regular mock tests and feedback sessions were invaluable in identifying my strengths and areas for improvement, allowing me to focus my efforts effectively. Thanks to Nanaska and Channa sir I not only passed my MCS exams with good marks but also gained a deeper understanding and appreciation of the subjects. I wholeheartedly recommend Nanaska to anyone seeking to excel in their CIMA exams.`,
		videoUrl: undefined,
		badge: undefined,
		isPrizeWinner: false,
		published: true,
		sortOrder: 11,
	},
	{
		studentName: `Pujani Sanjeewani`,
		country: `Sri Lanka`,
		flag: `🇱🇰`,
		tag: `MCS`,
		exam: `Management Case Study`,
		period: `May 2024`,
		year: 2024,
		marks: 90,
		imageUrl: `/images/2024-10-Pujani-MCS-copy.jpg`,
		quote: `I am immensely grateful to Nanaska for their exceptional support and guidance in helping me pass the CIMA Management case study exam with higher marks. The expertise and dedication of Mr. Channa Gunawardana and the team played a crucial role in my success. Their tailored approach and constant encouragement were invaluable. They went above and beyond to ensure I was well-prepared, providing me with the confidence and knowledge needed to excel. I highly recommend Nanaska to anyone seeking top-notch tutoring for CIMA. Their support truly makes a difference!`,
		videoUrl: undefined,
		badge: undefined,
		isPrizeWinner: false,
		published: true,
		sortOrder: 12,
	},
	{
		studentName: `Hiruni Hewage`,
		country: `Sri Lanka`,
		flag: `🇱🇰`,
		tag: `OCS`,
		exam: `Operational Case Study`,
		period: `May 2024`,
		year: 2024,
		marks: 94,
		imageUrl: `/images/2024-10-Untitled-2-9.jpg`,
		quote: `I would like to extend my heartfelt gratitude to the Nanaska team for their invaluable support in helping me complete my OCS exam. The well-structured mock exams and personalized feedback helped me identify and improve upon my weak areas, making me more confident and well-prepared for the exam. I am truly thankful for the dedication and commitment of the entire team, and I highly recommend Nanaska Institute to anyone seeking academic excellence.`,
		videoUrl: undefined,
		badge: undefined,
		isPrizeWinner: false,
		published: true,
		sortOrder: 13,
	},
	{
		studentName: `Imalsha Hikkaduwage`,
		country: `Sri Lanka`,
		flag: `🇱🇰`,
		tag: `OCS`,
		exam: `Operational Case Study`,
		period: `May 2024`,
		year: 2024,
		marks: 103,
		imageUrl: `/images/2024-10-Imalsha-ocs-copy.jpg`,
		quote: `Having done self-studies for all my prior OTQs I had no idea as to what the case study would hold and how to apply my knowledge to the case study examination. So with just one and a half months to go for my OCS I came across Nanaska. The mock papers that were given by Nanaska and the personalized feedback given on each paper not only boosted my confidence but also made the exam a breeze.`,
		videoUrl: undefined,
		badge: undefined,
		isPrizeWinner: false,
		published: true,
		sortOrder: 14,
	},
	{
		studentName: `Sanuda Minuraka`,
		country: `Sri Lanka`,
		flag: `🇱🇰`,
		tag: `SCS`,
		exam: `Strategic Case Study`,
		period: `Feb 2024`,
		year: 2024,
		marks: 99,
		imageUrl: `/images/2024-10-Untitled-2-7.jpg`,
		quote: `Appreciate all the guidance & support given by Channa sir and Nanaska Team to make my FLP journey a success and being able to finish off my CIMA journey in six months. The unwavering support by Team Nanaska carried me a long way by giving me a holistic exposure in my CIMA journey, all my gratitude and respect goes towards Channa sir & Nanaska.`,
		videoUrl: undefined,
		badge: undefined,
		isPrizeWinner: false,
		published: true,
		sortOrder: 15,
	},
	{
		studentName: `Upeshika Chathurangee`,
		country: `Sri Lanka`,
		flag: `🇱🇰`,
		tag: `SCS`,
		exam: `Strategic Case Study`,
		period: `Feb 2024`,
		year: 2024,
		marks: 83,
		imageUrl: `/images/2024-10-Untitled-2-6.jpg`,
		quote: `It was an amazing journey of becoming a CIMA CGMA passed finalist with Nanaska. Thanks to Channa sir, Mark sir, Ali sir and Nanaska team, I was able to get through all three examinations with first attempt. I specially would like to mention about their mock papers and one to one sessions. Those things were very helpful to all of my success. One on one guidance and results focused interaction really helped me to get through CIMA FLP. My heartiest wishes to Channa sir and Nanaska team!`,
		videoUrl: undefined,
		badge: undefined,
		isPrizeWinner: false,
		published: true,
		sortOrder: 16,
	},
	{
		studentName: `Chanuli Wijesinghe`,
		country: `Sri Lanka`,
		flag: `🇱🇰`,
		tag: `SCS`,
		exam: `Strategic Case Study`,
		period: `Feb 2024`,
		year: 2024,
		marks: 80,
		imageUrl: `/images/2024-10-Untitled-2-5.jpg`,
		quote: `During my CIMA journey, working with Nanaska was a true game-changer. Their persistent support, knowledgeable advice, and in-depth understanding of the subject matter were invaluable. I not only passed my CIMA tests but also became a more competent and knowledgeable professional as a result of Channa sir's teachings. I wholeheartedly recommend Nanaska to anyone seeking excellence in their CIMA journey.`,
		videoUrl: undefined,
		badge: undefined,
		isPrizeWinner: false,
		published: true,
		sortOrder: 17,
	},
	{
		studentName: `Lochan Kuruwita`,
		country: `Sri Lanka`,
		flag: `🇱🇰`,
		tag: `OCS`,
		exam: `Operational Case Study`,
		period: `Feb 2024`,
		year: 2024,
		marks: 92,
		imageUrl: `/images/2024-10-Untitled-2-8.jpg`,
		quote: `Nanaska have a great support system which is flexible and practical that we can do studies with our own pace! I'll recommend Nanaska to anyone who wishes to pursue CIMA through FLP!`,
		videoUrl: undefined,
		badge: undefined,
		isPrizeWinner: false,
		published: true,
		sortOrder: 18,
	},
	{
		studentName: `Daminda Bandara`,
		country: `Sri Lanka`,
		flag: `🇱🇰`,
		tag: `OCS`,
		exam: `Operational Case Study`,
		period: `Feb 2024`,
		year: 2024,
		marks: 90,
		imageUrl: `/images/2024-10-Daminda-1.jpg`,
		quote: `CIMA was a Start for Turning point in My Life — even having obtained few Professional and Academic qualifications, it was a very Hard Time to face this challenge while doing the Job. But during such time Nanaska became my second home. Lectures with their expanded knowledge and Academic Staff were Always behind us in technical and administrative supports. Mr. Osman Fernando always behind us as a Motivator and Guider, due to this personal attention by a Lecturer for Student was highly supported to overcome theoretical problems, its application and release work life stress situations quickly. The secret is the entire Nanaska Team.`,
		videoUrl: undefined,
		badge: undefined,
		isPrizeWinner: false,
		published: true,
		sortOrder: 19,
	},
	{
		studentName: `Aheshma Perera`,
		country: `Sri Lanka`,
		flag: `🇱🇰`,
		tag: `OCS`,
		exam: `Operational Case Study`,
		period: `Feb 2024`,
		year: 2024,
		marks: 87,
		imageUrl: `/images/2024-10-ashenma.jpg`,
		quote: `The reason I chose Nanaska as my tuition provider for the OCS was that the academic staff of Nanaska follow up and keep in touch with the students throughout the whole period, while encouraging us to finish every mock on time and by providing us tailor made guidance to improve our writing skills, techniques, speed and thinking pattern through productive methods such as one to one sessions and mock answers that are marked very detailed highlighting student weaknesses.`,
		videoUrl: undefined,
		badge: undefined,
		isPrizeWinner: false,
		published: true,
		sortOrder: 20,
	},
	{
		studentName: `Shernaya Morel`,
		country: `Sri Lanka`,
		flag: `🇱🇰`,
		tag: `OCS`,
		exam: `Operational Case Study`,
		period: `Nov 2023`,
		year: 2023,
		marks: 112,
		imageUrl: `/images/2024-10-OCS-Shernaya-Senorine-Morel-1.jpg`,
		quote: `Nanaska Institute truly provided invaluable support and guidance in my preparation for the OCS exam. The lecturers' unwavering efforts from excellent study materials to personalized attention helped me gain a better understanding of the material. I wholeheartedly recommend Nanaska Institute for anyone aspiring to excel in their pursuit of CIMA certification.`,
		videoUrl: undefined,
		badge: undefined,
		isPrizeWinner: false,
		published: true,
		sortOrder: 21,
	},
	{
		studentName: `Udula Subodha`,
		country: `Sri Lanka`,
		flag: `🇱🇰`,
		tag: `SCS`,
		exam: `Strategic Case Study`,
		period: `Nov 2023`,
		year: 2023,
		marks: 81,
		imageUrl: `/images/2025-08-Udula-Subodha-e1754311089359.jpg`,
		quote: `I would like to really thank you for the Channa sir as well as other two lecturers for their highest support throughout this period. Without your support, I would not be able to complete this final case study examination. Again thank you so much academic and Non academic staff who were dedicated on behalf of our students to enhance their knowledge and skills to finish this CIMA Examinations. Channa sir, the consent you delivered for us "Fight, Fight, Fight, until the last minute, Last second. Do not give up", really helped me to pass the exam.`,
		videoUrl: undefined,
		badge: undefined,
		isPrizeWinner: false,
		published: true,
		sortOrder: 22,
	},
	{
		studentName: `Dimitra Perera`,
		country: `Sri Lanka`,
		flag: `🇱🇰`,
		tag: `SCS`,
		exam: `Strategic Case Study`,
		period: `Nov 2023`,
		year: 2023,
		marks: 84,
		imageUrl: `/images/2024-10-SCS-G.S.Dimitra-Perera.jpg`,
		quote: `I joined Nanaska Institute midway through their November Strategic Case Study lectures. In three weeks, Mr. Channa Gunawardana and the lecture panel was able to prepare me with the necessary skills, knowledge, competencies and industry specific knowledge required to successfully pass the exam. I would like to sincerely thank everyone at Nanaska for coaching me in those three short weeks and helping me pass on my very first attempt.`,
		videoUrl: undefined,
		badge: undefined,
		isPrizeWinner: false,
		published: true,
		sortOrder: 23,
	},
	{
		studentName: `Mehara Jayalath`,
		country: `Sri Lanka`,
		flag: `🇱🇰`,
		tag: `SCS`,
		exam: `Strategic Case Study`,
		period: `Nov 2023`,
		year: 2023,
		marks: 86,
		imageUrl: `/images/2024-10-SCS-Mehara-Jayalath.jpg`,
		quote: `The knowledge and support given from Nanaska made me face the exam with confidence. This journey not just helped me pass the SCS exam but also trained me to solve real life corporate problems. I am forever grateful for Mr Channa for the motivation, exam techniques and for his unique teaching methods.`,
		videoUrl: undefined,
		badge: `A Star Program`,
		isPrizeWinner: false,
		published: true,
		sortOrder: 24,
	},
	{
		studentName: `Menaka Jesudasan`,
		country: `Sri Lanka`,
		flag: `🇱🇰`,
		tag: `OCS`,
		exam: `Operational Case Study`,
		period: `Nov 2023`,
		year: 2023,
		marks: 97,
		imageUrl: `/images/2024-10-OCS-Menaka-Jesudasan-1.jpg`,
		quote: `I'm Menaka Niroshani who has done my OCS Nov 23 with Nanaska… I must say that it was an incredible journey and I cleared my OCS today. My heartfelt thanks goes to the OCS lecturer Mr. Mark and Mr. Osmand who supported throughout the journey and the whole Nanaska team. Wishing Nanaska team all the best for the future.`,
		videoUrl: undefined,
		badge: undefined,
		isPrizeWinner: false,
		published: true,
		sortOrder: 25,
	},
	{
		studentName: `Nethmi Kosmullage`,
		country: `Sri Lanka`,
		flag: `🇱🇰`,
		tag: `MCS`,
		exam: `Management Case Study`,
		period: `Nov 2023`,
		year: 2023,
		marks: 86,
		imageUrl: `/images/2024-10-IMG_1256.jpg`,
		quote: `When it comes to MCS, Channa sir's teaching style helped me a lot to get through the exam without studying theory areas in depth and it's like a miracle to me. So I'm forever grateful for choosing Nanaska as the tuition provider for my CIMA journey.`,
		videoUrl: undefined,
		badge: undefined,
		isPrizeWinner: false,
		published: true,
		sortOrder: 26,
	},
	{
		studentName: `Pawani Perera`,
		country: `Sri Lanka`,
		flag: `🇱🇰`,
		tag: `OCS`,
		exam: `Operational Case Study`,
		period: `Nov 2023`,
		year: 2023,
		marks: 90,
		imageUrl: `/images/2024-10-Untitled-2-4.jpg`,
		quote: `I wanted to express my sincere gratitude for Nanaska for the support throughout the CIMA Operational Case Study. The guidance and expertise played a pivotal role in my success, and I am truly thankful for the teaching and commitment to my success.`,
		videoUrl: undefined,
		badge: undefined,
		isPrizeWinner: false,
		published: true,
		sortOrder: 27,
	},
	{
		studentName: `Kolinda Lasantha`,
		country: `New Zealand`,
		flag: `🇳🇿`,
		tag: `OCS`,
		exam: `Operational Case Study`,
		period: `Aug 2023`,
		year: 2023,
		marks: undefined,
		imageUrl: `/images/2024-10-412064022_389492800121908_8493321068356738755_n.jpg`,
		quote: `When I joined Nanaska, passing the OCS exam was just a dream, but Nanaska helped me achieve it. The lecturers provided excellent support through online classes, mock exams, and high-quality study materials. I am especially grateful to Mr. Mark Gunathilaka and Mr. Osmand Fernando for helping me achieve my goal of becoming CIMA certified while working full-time as an accountant. I highly recommend Nanaska Institute to anyone considering pursuing CIMA certification.`,
		videoUrl: undefined,
		badge: undefined,
		isPrizeWinner: false,
		published: true,
		sortOrder: 28,
	},
	{
		studentName: `Piyumi Divyanjali`,
		country: `Sri Lanka`,
		flag: `🇱🇰`,
		tag: `SCS`,
		exam: `Strategic Case Study`,
		period: `May 2023`,
		year: 2023,
		marks: 103,
		imageUrl: `/images/2024-10-Untitled-2.jpg`,
		quote: `I appreciate the enormous support offered by Nanaska team for me to pass the Strategic Level case study with a good score. I completed my OTQ exams two years ago and was doubtful about my chances of passing the SCS exam without a clear memory of the subjects. Nonetheless, the holistic approach followed by Channa Sir and staff while giving personal attention to each student was very helpful and it was one of the fundamental reasons behind my success. I am really grateful for Nanaska team for all the efforts behind these achievements.`,
		videoUrl: undefined,
		badge: undefined,
		isPrizeWinner: false,
		published: true,
		sortOrder: 29,
	},
	{
		studentName: `Fathima Shifara`,
		country: `Sri Lanka`,
		flag: `🇱🇰`,
		tag: `OCS`,
		exam: `Operational Case Study`,
		period: `May 2023`,
		year: 2023,
		marks: 97,
		imageUrl: `/images/2024-10-Untitled-2-2.jpg`,
		quote: `I just want to express my heartfelt thanks to Nanaska for their incredible CIMA case study program. The support I received—from expert lecturers to personalized guidance and their amazing exam practice tools—made all the difference in my success. Nanaska goes beyond just helping you pass; they build you into a confident, capable leader. Thanks to their program, I passed my case study exam with confidence, and I know I'm better prepared for the future. Thank you for all the support and extra efforts given to pass the exam.`,
		videoUrl: undefined,
		badge: undefined,
		isPrizeWinner: false,
		published: true,
		sortOrder: 30,
	},
	{
		studentName: `Eugene Akorli`,
		country: `Ghana`,
		flag: `🇬🇭`,
		tag: `OCS`,
		exam: `Operational Case Study`,
		period: `May 2023`,
		year: 2023,
		marks: 93,
		imageUrl: `/images/2024-10-Untitled-2-3.jpg`,
		quote: `Leading up to the OCS exam I had struggled with P1 (management accounting), failing once and postponing a couple of times before eventually passing. And so when I learnt the OCS will be heavily based on P1 theory I was really nervous but a friend recommended Nanaska and I decided to put my trust in them and it paid off! The teaching methods used by Nanaska helped me to believe that if I put in the required effort I could achieve the result I wanted. All I had to do was follow their lessons, complete the tasks we were assigned and I saw myself growing in confidence. The responsiveness and dedication of the team at Nanaska proved really valuable and made me feel that I had all the support I needed to pass the exam. I'm very grateful to the team and I look forward to benefiting from their tutelage again in future exams.`,
		videoUrl: undefined,
		badge: `Prize Winner`,
		isPrizeWinner: true,
		published: true,
		sortOrder: 31,
	},
	{
		studentName: `Tharanga Dasanayake`,
		country: `Sri Lanka`,
		flag: `🇱🇰`,
		tag: `OCS`,
		exam: `Operational Case Study`,
		period: `May 2023`,
		year: 2023,
		marks: undefined,
		imageUrl: `/images/2024-10-438952929_457554139982440_4300828445761488087_n-copy.jpg`,
		quote: `NANASKA made me feel in safe hands in my CIMA journey with their wonderful ways of teaching. They are a true specialist in CIMA case study exams. Even as a busy manager in a private sector company who has no Finance background, I was really successful in getting through my OCS exam quite comfortably. I would like to thank NANASKA team for their wonderful support in my success.`,
		videoUrl: undefined,
		badge: undefined,
		isPrizeWinner: false,
		published: true,
		sortOrder: 32,
	},
	{
		studentName: `Nethra Fernando`,
		country: `Sri Lanka`,
		flag: `🇱🇰`,
		tag: `MCS`,
		exam: `Management Case Study (CSEP Pathway)`,
		period: `Feb 2021`,
		year: 2021,
		marks: undefined,
		imageUrl: `/images/2021-06-nethra.jpg`,
		quote: `Nanaska's focused approach on improving individuals has worked for me. Not only did Nanaska provide a unique educational service leveraging digitalization, they were right there for me encouraging and mentoring in difficult times. With their holistic approach in preparing for CIMA Case Study, you simply can't go wrong. Thank you, Channa, Wathsala and the Team. Wishing Nanaska for much greater endeavors.`,
		videoUrl: undefined,
		badge: undefined,
		isPrizeWinner: false,
		published: true,
		sortOrder: 33,
	},
	{
		studentName: `Senthil Nathan`,
		country: `Thailand`,
		flag: `🇹🇭`,
		tag: `SCS`,
		exam: `Strategic Case Study`,
		period: `Feb 2021`,
		year: 2021,
		marks: undefined,
		imageUrl: `/images/2021-06-Senthil.jpg`,
		quote: `I would like to convey my sincere thanks and appreciation for all the supports that you have provided for my CIMA SCS exam, with all your great support I have cleared my exam in the first attempt. Even though I enrolled with CIMA April-2020 I haven't sat for my exam until Feb-2021, due to my work load. Mr. Channa's way of teaching and the mock exam feedback provided by Ishara and Wathsala was very useful and encouraged me to focus on my studies to improve and get ready for the real exam.`,
		videoUrl: undefined,
		badge: undefined,
		isPrizeWinner: false,
		published: true,
		sortOrder: 34,
	},
	{
		studentName: `Ishara Sandamali Gamage`,
		country: `Sri Lanka`,
		flag: `🇱🇰`,
		tag: `OCS`,
		exam: `Operational Case Study`,
		period: `Feb 2021`,
		year: 2021,
		marks: undefined,
		imageUrl: `/images/2021-06-Ishara.jpg`,
		quote: `After completing my Master's degree I joined Nanaska Institute for OCS classes as the very first step of my CIMA journey. It was an amazing experience for me to see how the lecturers of Nanaska helped the students to go through the exams successfully by adhering to various online platforms like online classes, mock exams and via Nanaska website enriched with high quality study materials. I shall be very much thankful to the lecturers of Nanaska Institute, especially to Mr. Channa Gunawardana & Mr. Mark Gunathilaka for their painstaking effort to improve the knowledge & for the motivation extended throughout.`,
		videoUrl: undefined,
		badge: undefined,
		isPrizeWinner: false,
		published: true,
		sortOrder: 35,
	},
	{
		studentName: `Asela Emilius Theverapperuma`,
		country: `Sri Lanka`,
		flag: `🇱🇰`,
		tag: `MCS`,
		exam: `Management Case Study (CSEP Pathway)`,
		period: `Feb 2021`,
		year: 2021,
		marks: undefined,
		imageUrl: `/images/2021-06-Asela-photo2.jpg`,
		quote: `Studying through an online platform was a first time experience for me. NANASKA's teaching methodology and the resources they provide to get me thinking in the right direction were the key attributes that contributed to my success. Coming into the CIMA program from the C-SEP route I had to learn the basics as well whilst preparing for the Case Study. Channa's TEAM managed to make this a simpler task than I expected. Some of the facilities that I found interesting and value adding were the personal attention, any time any place video availability, and the online mocks.`,
		videoUrl: undefined,
		badge: undefined,
		isPrizeWinner: false,
		published: true,
		sortOrder: 36,
	},
	{
		studentName: `Ranjitkumar Thivakaran`,
		country: `Australia`,
		flag: `🇦🇺`,
		tag: `SCS`,
		exam: `Strategic Case Study`,
		period: `Feb 2021`,
		year: 2021,
		marks: undefined,
		imageUrl: `/images/2021-06-Thivakaran-scaled.jpg`,
		quote: `Coming together is a beginning, Keeping together is progress, Working together is success — Henry Ford. I resumed my strategic level case study exam from old syllabus to new syllabus. I got to know that Channa is doing classes online then I was enrolled for the session. From the start of the session, the objective was clear that Nanaska team want all of us to see success in the exam. Industry knowledge and theoretical explanation are the core of the session. As the progress goes on mock papers played a key role to understand the exam condition and also to understand our mistakes in writing an answer. I highly recommend students who are seeking for their success in CIMA exams to be associated with Nanaska institution.`,
		videoUrl: undefined,
		badge: undefined,
		isPrizeWinner: false,
		published: true,
		sortOrder: 37,
	},
	{
		studentName: `Kirit Kumar`,
		country: `Malaysia`,
		flag: `🇲🇾`,
		tag: `SCS`,
		exam: `Strategic Case Study`,
		period: `Feb 2021`,
		year: 2021,
		marks: undefined,
		imageUrl: `/images/2021-06-Kirith-Rumar.jpg`,
		quote: `It was indeed a great pleasure being introduced to Nanaska by CIMA. Being a person who have left studies for decades & only 6 weeks given to prepare for the final exam is very challenging. I took every lesson given by Mr. Channa very seriously & revised all the notes provided regularly. The mock papers are important tools for me to get prepared for the final exam. Nanaska has played a major role in turning a person like me from no one to someone today & this exam was my very first & I have managed to pass in first sitting. Nanaska has made great sacrifices in conducting long hour classes and this actually turned their sacrifice into fruitful as I managed to clear at first sitting.`,
		videoUrl: undefined,
		badge: undefined,
		isPrizeWinner: false,
		published: true,
		sortOrder: 38,
	},
	{
		studentName: `Ramaly Rahuman`,
		country: `Sri Lanka`,
		flag: `🇱🇰`,
		tag: `MCS`,
		exam: `Management Case Study`,
		period: `Feb 2021`,
		year: 2021,
		marks: undefined,
		imageUrl: `/images/2021-06-Ramaly.jpg`,
		quote: `Attempting case study was a daunting task for me. Nanaska did everything. The best part was that I could completely trust their team. The course covered a lot of information, delivered in concise chunks that were easy to absorb. The structure was clear, logical and effective. The deep dive, Power mocks, Financial mocks, Refresh theories played a vital role. The main benefits came from doing plenty of mock papers and receiving individual feedback. I am looking forward to working with Mr. Channa and Nanaska for Strategy level exams and I strongly recommend Nanaska for other students as well.`,
		videoUrl: undefined,
		badge: undefined,
		isPrizeWinner: false,
		published: true,
		sortOrder: 39,
	},
	{
		studentName: `Antony Nimesh Jayawardena`,
		country: `UAE`,
		flag: `🇦🇪`,
		tag: `SCS`,
		exam: `Strategic Case Study`,
		period: `Nov 2020`,
		year: 2020,
		marks: undefined,
		imageUrl: `/images/2021-06-Nimesh.jpg`,
		quote: `I joined CIMA through the CIMA Gateway programme. Thanks to Mr. Channa and Nanaska, revision sessions were organized which gave me an excellent overall view and knowledge on the theory subjects. From the beginning of the SCS case study Mr. Channa trained us to think practically which was the essence for my success in SCS case study. The programme was well structured which contained more than 5 mock exams, summarizing of the case study, Possible questions and an overall view of the industry. Nanaska even went up to the extent of having sessions by experts in the related industry. I highly recommend Nanaska to prospective students who are eager to achieve success in the Corporate world.`,
		videoUrl: undefined,
		badge: `Joint Country Prize Winner`,
		isPrizeWinner: true,
		published: true,
		sortOrder: 40,
	},
	{
		studentName: `Luong Thi Thuy Linh`,
		country: `Malaysia`,
		flag: `🇲🇾`,
		tag: `SCS`,
		exam: `Strategic Case Study`,
		period: `Nov 2020`,
		year: 2020,
		marks: undefined,
		imageUrl: `/images/2021-06-Luong-Thi-Thuy-Linh-Malaysia.jpg`,
		quote: `I am very grateful for what Nanaska had prepared for my Strategic Case Study exam. Thank you, Mr. Channa and Nanaska team for the inspiring lectures, the comprehensive and unique learning materials as well as the one to one coaching sections after each mock exam.`,
		videoUrl: undefined,
		badge: `Country Prize Winner`,
		isPrizeWinner: true,
		published: true,
		sortOrder: 41,
	},
	{
		studentName: `Naveed Anjoon`,
		country: `Sri Lanka`,
		flag: `🇱🇰`,
		tag: `MCS`,
		exam: `Management Case Study (CSEP Pathway)`,
		period: `Nov 2020`,
		year: 2020,
		marks: undefined,
		imageUrl: `/images/2021-06-Naveed.jpeg`,
		quote: `As a Senior Sales and Marketing professional and someone who didn't do any exams in the last 5 years, I had my own doubts whether I'll be able to pass the exams in one go. I consider myself lucky to have joined Nanaska as it gave me the full confidence within the first couple of weeks itself that it is possible to pass the exams provided we put in the hard work. And I DID GET THROUGH! The structure used, ground rules, deep dives, mock papers provided, theory revision and the 1-2-1 feedback sessions were phenomenal. I have no hesitation in recommending Nanaska for CIMA education.`,
		videoUrl: undefined,
		badge: undefined,
		isPrizeWinner: false,
		published: true,
		sortOrder: 42,
	},
	{
		studentName: `Nason Zhang`,
		country: `Sri Lanka`,
		flag: `🇱🇰`,
		tag: `MCS`,
		exam: `Management Case Study (CSEP Pathway)`,
		period: `Nov 2020`,
		year: 2020,
		marks: undefined,
		imageUrl: `/images/2021-06-Nason-Zhang-CICT.jpg`,
		quote: `It's a great and fruitful journey with Nanaska Team in pursuing the achievement of CIMA. Mr. Channa's class is an excellent combination of theoretical knowledge and modern practice. The work experience shared, the industrial leader seminar held, abundant network resources, the individual study guidance group — with quite a lot encouragement and supervision — would be the most advantageous tools not only in passing CIMA exam, but also in improving your Financial Profession.`,
		videoUrl: undefined,
		badge: undefined,
		isPrizeWinner: false,
		published: true,
		sortOrder: 43,
	},
	{
		studentName: `Hasini Erangika`,
		country: `Sri Lanka`,
		flag: `🇱🇰`,
		tag: `MCS`,
		exam: `Management Case Study`,
		period: `Aug 2020`,
		year: 2020,
		marks: undefined,
		imageUrl: `/images/2021-06-p2.png`,
		quote: `Mr. Channa from NANASKA led me on my CIMA journey. NANASKA prepared me for the CIMA SCS exam by providing me with the requisite subject information, study notes, time management skills, and exam strategy to pass the CIMA SCS exam with flying colours. Mr. Channa's online classes and notes, which included KYP, KYI, refresh theory, Deep Dive, podcasts, and mock exams, laid a strong foundation for taking the exam. Nanaska comes highly recommended by me.`,
		videoUrl: undefined,
		badge: undefined,
		isPrizeWinner: false,
		published: true,
		sortOrder: 44,
	},
	{
		studentName: `Nilhan Perera`,
		country: `Sri Lanka`,
		flag: `🇱🇰`,
		tag: `MCS`,
		exam: `Management Case Study`,
		period: `Aug 2020`,
		year: 2020,
		marks: undefined,
		imageUrl: `/images/2021-06-42059622_10217225943069133_3879775985771479040_n.jpg`,
		quote: `I started my CIMA journey through the Management Case study from the Gateway route. Channa and the team immensely helped me as I had to cover all three theory areas since I didn't do the OTQs, but Nanaska has a superlative forum which gave access to me and that had every tool that I needed to get through the exam. Personal one to one session was a big turning point in motivating me and it also gave me a clear opportunity to clear my doubts. Team Nanaska has a true passion and commitment to what they do so I would highly recommend Nanaska to any prospective student looking to study CIMA.`,
		videoUrl: undefined,
		badge: undefined,
		isPrizeWinner: false,
		published: true,
		sortOrder: 45,
	},
	{
		studentName: `Jimson George`,
		country: `Oman`,
		flag: `🇴🇲`,
		tag: `SCS`,
		exam: `Strategic Case Study`,
		period: `Aug 2020`,
		year: 2020,
		marks: undefined,
		imageUrl: `/images/2021-06-WhatsApp-Image-2021-04-18-at-8.35.12-PM.jpg`,
		quote: `With Nanaska I could pass the Management Level Case study exam in my first attempt. They have planned everything in advance in order to support us to get through this. Also they have a team who are very supportive and they have directly advised me regarding the areas to improve at one to one session. I am really thankful to Channa sir and the Nanaska team who supported me throughout this journey and wish they could guide many more students toward success.`,
		videoUrl: undefined,
		badge: undefined,
		isPrizeWinner: false,
		published: true,
		sortOrder: 46,
	},
	{
		studentName: `Godwin Gyimah`,
		country: `Ghana`,
		flag: `🇬🇭`,
		tag: `MCS`,
		exam: `Management Case Study`,
		period: `Aug 2020`,
		year: 2020,
		marks: undefined,
		imageUrl: `/images/2021-06-attachment1.jpg`,
		quote: `I had a very great experience with Nanaska and that helped me pass my gateway exams. Firstly, I had not studied accounting before I joined CIMA — I have an engineering degree, MBA, and work as an HR professional. With the help of Nanaska's learning approach and how they prepared me for the exams, I passed on my first attempt. Nanaska webinars and mocks were very helpful to give you a feel of how the exam day looks like and made me relaxed during the exams. The team was also helpful in providing relevant information regularly in a different form which allowed for different approaches to learning.`,
		videoUrl: undefined,
		badge: undefined,
		isPrizeWinner: false,
		published: true,
		sortOrder: 47,
	},
	{
		studentName: `Vinesh Moodley`,
		country: `Sri Lanka`,
		flag: `🇱🇰`,
		tag: `MCS`,
		exam: `Management Case Study`,
		period: `May 2020`,
		year: 2020,
		marks: undefined,
		imageUrl: `/images/2021-06-Vinesh-Moodley-1-_-United-Arab-Emirates-1.jpg`,
		quote: `I successfully passed both the MCS and SCS exams during 2020 with Nanaska as my tuition provider. Studying remotely and online especially during 2020 was really challenging but partnering with a tuition provider like Nanaska allowed me to fulfil my increased work commitments as well as keep up to date with my studies. Channa's practical experience and his ability to combine this with the theory required is top class and a crucial aspect to success in the CIMA exams. His dedication and passion for the subject matter is truly inspiring and certainly helped me to be successful. I have no hesitation in recommending Nanaska as a preferred CIMA tuition provider.`,
		videoUrl: undefined,
		badge: undefined,
		isPrizeWinner: false,
		published: true,
		sortOrder: 48,
	},
	{
		studentName: `Narmatha Murali`,
		country: `UK`,
		flag: `🇬🇧`,
		tag: `SCS`,
		exam: `Strategic Case Study`,
		period: `May 2017`,
		year: 2017,
		marks: 102,
		imageUrl: `/images/2021-06-Narmatha.png`,
		quote: `I enrolled in Nanaska's online programme to help with my SCS exam which I failed to get through in my previous two attempts. The support and guidance from the lecturer has helped me to pass this paper with 102 scores. Setting aside time to study for a professional exam had been a challenge for me. Nanaska's programme provided the flexibility to juggle around my work, family and studies. The weekly follow up sessions are really motivational in terms of keeping you ahead of the game and broaden your thinking. The feed back for mock papers are very useful in identifying the areas where you need improvement. The level of support and motivation given to students by Nanaska team is truly amazing!!`,
		videoUrl: undefined,
		badge: undefined,
		isPrizeWinner: false,
		published: true,
		sortOrder: 49,
	},
	{
		studentName: `Emomotimi Agama`,
		country: `Nigeria`,
		flag: `🇳🇬`,
		tag: `SCS`,
		exam: `Strategic Case Study`,
		period: `May 2017`,
		year: 2017,
		marks: undefined,
		imageUrl: `/images/2021-06-Agama.png`,
		quote: `Thanks to Nanaska for the plan put in place to ensure my success. The level of personal involvement of the facilitator and the constant nudging provided me with a great deal of materials that helped me achieve my goal. The emphasis on particular areas is very important and any student that desires to pass must take these points seriously. There is no option to starting early in your preparation as this will enable you cover all the areas you are expected to cover and give room for strategic revision. Will recommend Nanaska to anyone, any day and anytime.`,
		videoUrl: undefined,
		badge: undefined,
		isPrizeWinner: false,
		published: true,
		sortOrder: 50,
	},
	{
		studentName: `Patricia Duru`,
		country: `Nigeria`,
		flag: `🇳🇬`,
		tag: `SCS`,
		exam: `Strategic Case Study`,
		period: `May 2017`,
		year: 2017,
		marks: undefined,
		imageUrl: `/images/2021-06-Patricia.jpg`,
		quote: `Thank you Nanaska (LearnCIMA) for making my first attempt at Strategic Case Study a successful one. The training methodology is undeniably unique and very effective considering the tight work schedule of most students. The podcasts, weekly live discussion sessions with Channa, WhatsApp group chats, mocks written in simulated CIMA exam portal, one-on-one sessions for review of mocks, access to a rich study library etc. are viable tools that facilitate success of students at the CIMA exams. Well done team Nanaska!`,
		videoUrl: undefined,
		badge: undefined,
		isPrizeWinner: false,
		published: true,
		sortOrder: 51,
	},
	{
		studentName: `Adegbite Adekola`,
		country: `Nigeria`,
		flag: `🇳🇬`,
		tag: `SCS`,
		exam: `Strategic Case Study`,
		period: `May 2017`,
		year: 2017,
		marks: undefined,
		imageUrl: `/images/2021-06-p2.png`,
		quote: `I took the SCS with a different tutor last year. He spent only one weekend to go over the material; the rest was left to me to figure out. That partnership failed. This year, I went for Nanaska. From the get-go, I knew they were different: website, personal profiles, proper admin, podcasts, etc. Then it came time to deep dive; we met regularly, lots of reading material, and WhatsApp forum. We had webinars every weekend to go over new information and questions from the week. We then progressed to the practice mocks with one-on-one feedback. Success was resounding.`,
		videoUrl: undefined,
		badge: undefined,
		isPrizeWinner: false,
		published: true,
		sortOrder: 52,
	},
	{
		studentName: `Tin Mar Yi`,
		country: `Myanmar`,
		flag: `🇲🇲`,
		tag: `SCS`,
		exam: `Strategic Case Study`,
		period: `May 2017`,
		year: 2017,
		marks: undefined,
		imageUrl: `/images/2021-06-Tin.png`,
		quote: `Before I knew about Nanaska and Mr. Channa, I was the person who does not have the enough level of confidence to pass the CIMA SCS exam. With the support of Channa Sir and Nanaska team, through the mock exams, I knew about my strengths and weaknesses of my knowledge and experience to face the real exam. When I sat the real exam, I noticed that I could manage the time and answering points that pushed me to pass the exam. With Nanaska and Channa Sir's support, I could pass the exam. I strongly believe that Nanaska has the best method to pass the SCS exam.`,
		videoUrl: undefined,
		badge: undefined,
		isPrizeWinner: false,
		published: true,
		sortOrder: 53,
	},
];

async function main() {
	console.log('Seeding admin users …');
	for (const admin of adminUsers) {
		const passwordHash = await bcrypt.hash(admin.password, SALT_ROUNDS);
		await prisma.adminUser.upsert({
			where: { email: admin.email },
			update: { name: admin.name, role: admin.role, passwordHash },
			create: { email: admin.email, name: admin.name, role: admin.role, passwordHash },
		});
	}

	console.log('Seeding lecturers …');
	for (const l of lecturers) {
		const existing = await prisma.lecturer.findFirst({ where: { name: l.name } });
		if (existing) {
			await prisma.lecturer.update({
				where: { id: existing.id },
				data: { ...l, stats: l.stats as any },
			});
		} else {
			await prisma.lecturer.create({ data: { ...l, stats: l.stats as any } });
		}
	}

	console.log('Seeding site settings …');
	for (const setting of defaultSettings) {
		await prisma.siteSetting.upsert({
			where: { key: setting.key },
			update: { label: setting.label, category: setting.category },
			create: setting,
		});
	}

	console.log('Seeding courses …');
	for (const s of subjects) {
		const { syllabus, highlights, outcomes, ...rest } = s as any;
		const courseData = {
			...rest,
			highlights: highlights || [],
			syllabus: syllabus ? (syllabus as any) : [],
			outcomes: outcomes || [],
		};
		await prisma.course.upsert({
			where: { id: s.id },
			update: courseData,
			create: courseData,
		});
	}

	console.log('Seeding combinations …');
	for (const c of combinations) {
		const comboName = (c as any).name || '';
		const comboSlug = (c as any).slug || undefined;
		const comboPriceGbp = (c as any).priceGbp || 0;

		// Build update data (no slug to avoid unique constraint issues)
		const updateData: any = {
			level: c.level,
			price: c.price,
			priceGbp: comboPriceGbp,
			name: comboName,
		};

		// Build create data (include slug only if defined)
		const createData: any = {
			id: c.id,
			level: c.level,
			price: c.price,
			priceGbp: comboPriceGbp,
			name: comboName,
		};
		if (comboSlug) {
			createData.slug = comboSlug;
		}

		await prisma.courseCombination.upsert({
			where: { id: c.id },
			update: updateData,
			create: createData,
		});

		for (const courseId of c.subjects) {
			await prisma.courseCombinationItem.upsert({
				where: { combinationId_courseId: { combinationId: c.id, courseId } },
				update: {},
				create: { combinationId: c.id, courseId },
			});
		}
	}

	console.log('Seeding testimonials …');
	for (const t of testimonials) {
		const existing = await prisma.testimonial.findFirst({
			where: { studentName: t.studentName, period: t.period },
		});
		if (!existing) {
			await prisma.testimonial.create({ data: t as any });
		}
	}

	console.log('Seeding site images …');
	const siteImages = [
		// Hero slider (1916×792 approx banner dimensions)
		{ key: 'hero_slide_1', group: 'hero', label: 'Hero Slide 1', url: '/images/2026-03-HomePage-Dekstop.png', altText: 'Nanaska – Leading CIMA Course Provider', widthHint: 1916, heightHint: 792, sortOrder: 1 },
		{ key: 'hero_slide_2', group: 'hero', label: 'Hero Slide 2', url: '/images/2025-11-Desktop.webp', altText: 'Nanaska CIMA Courses', widthHint: 1916, heightHint: 792, sortOrder: 2 },
		{ key: 'hero_slide_3', group: 'hero', label: 'Hero Slide 3', url: '/images/2025-10-resize-web.webp', altText: 'Nanaska Students', widthHint: 1916, heightHint: 792, sortOrder: 3 },
		{ key: 'hero_slide_4', group: 'hero', label: 'Hero Slide 4', url: '/images/2025-10-Prize-Winner-yanik-web-1.webp', altText: 'Prize Winner', widthHint: 1916, heightHint: 792, sortOrder: 4 },
		{ key: 'hero_slide_5', group: 'hero', label: 'Hero Slide 5', url: '/images/2025-10-Nanaska_September_lecture_panel_Slider.webp', altText: 'September Lecture Panel', widthHint: 1916, heightHint: 792, sortOrder: 5 },
		{ key: 'hero_slide_6', group: 'hero', label: 'Hero Slide 6', url: '/images/2025-10-Nanska_Prize_winner_Template-v2_Banner.webp', altText: 'Prize Winner Template', widthHint: 1916, heightHint: 792, sortOrder: 6 },
		{ key: 'hero_slide_7', group: 'hero', label: 'Hero Slide 7', url: '/images/2025-10-Nanaska_CIMA-Prize-Winner-Slider-1916x792-1.webp', altText: 'CIMA Prize Winner', widthHint: 1916, heightHint: 792, sortOrder: 7 },
		{ key: 'hero_slide_8', group: 'hero', label: 'Hero Slide 8', url: '/images/2026-01-100-Club-MCS-02-Web-banner.webp', altText: '100 Club MCS', widthHint: 1916, heightHint: 792, sortOrder: 8 },
		{ key: 'hero_slide_9', group: 'hero', label: 'Hero Slide 9', url: '/images/2026-01-Prize-Winner-Kaneshamoorthy-Anochkaran-wb-1.png', altText: 'Prize Winner Kaneshamoorthy', widthHint: 1916, heightHint: 792, sortOrder: 9 },
		// Course level images (roughly 600×400)
		{ key: 'course_certificate', group: 'courses', label: 'Certificate Level', url: '/images/2021-03-cert-level.jpg', altText: 'CIMA Certificate Level', widthHint: 600, heightHint: 400, sortOrder: 1 },
		{ key: 'course_operational', group: 'courses', label: 'Operational Level', url: '/images/2021-03-opera-level.jpg', altText: 'CIMA Operational Level', widthHint: 600, heightHint: 400, sortOrder: 2 },
		{ key: 'course_management', group: 'courses', label: 'Management Level', url: '/images/2021-03-manage-level.jpg', altText: 'CIMA Management Level', widthHint: 600, heightHint: 400, sortOrder: 3 },
		{ key: 'course_strategic', group: 'courses', label: 'Strategic Level', url: '/images/2021-03-strat-level.jpg', altText: 'CIMA Strategic Level', widthHint: 600, heightHint: 400, sortOrder: 4 },
		// Features section images (480×320 approx)
		{ key: 'feature_tutoring', group: 'features', label: 'Feature: Personalised Tutoring', url: 'https://images.unsplash.com/photo-1571260899304-425eee4c7efc?w=480&q=80', altText: 'Personalised tutoring session', widthHint: 480, heightHint: 320, sortOrder: 1 },
		{ key: 'feature_online', group: 'features', label: 'Feature: Online & On-site Classes', url: 'https://images.unsplash.com/photo-1587620962725-abab7fe55159?w=480&q=80', altText: 'Online learning on laptop', widthHint: 480, heightHint: 320, sortOrder: 2 },
		{ key: 'feature_materials', group: 'features', label: 'Feature: Study Materials', url: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=480&q=80', altText: 'Study materials and books', widthHint: 480, heightHint: 320, sortOrder: 3 },
		{ key: 'feature_support', group: 'features', label: 'Feature: Student Support', url: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=480&q=80', altText: 'Dedicated student support team', widthHint: 480, heightHint: 320, sortOrder: 4 },
	];

	for (const img of siteImages) {
		await prisma.siteImage.upsert({
			where: { key: img.key },
			update: {},
			create: img,
		});
	}

	console.log('Seed complete ✓');
}

main()
	.catch((e) => {
		console.error(e);
		process.exit(1);
	})
	.finally(async () => {
		await prisma.$disconnect();
	});
